#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

# Relative path to `working_dir` in `docker-compose.yml` is used.
# Absolute path, ${PROJECT_DIR}/${BACKEND_DIR}/, can also be used.
mkdir -p node_modules vendor \
    && chown -R sail:sail node_modules vendor

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
